# Build the snap on pull_request to ensure the snap is buildable before merge to main
name: Test Build Snap

on:
  pull_request:

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
  LAUNCHPAD_TOKEN: ${{ secrets.LAUNCHPAD_TOKEN }}

jobs:
  local-build:
    name: Build snap (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ "ubuntu-latest", "Ubuntu_ARM64_4C_16G_03" ]
        include:
        - runner: "ubuntu-latest"
          platform: amd64
        - runner: "Ubuntu_ARM64_4C_16G_03"
          platform: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: latest/stable

      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft

      - name: Build Snap
        run: snapcraft pack
      
      - name: Upload snap
        uses: actions/upload-artifact@v5
        with:
          name: prometheus-blackbox-exporter-${{ matrix.platform }}-snap
          path: "*.snap"

  remote-build:
    name: Build snap (${{ matrix.build-for }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-for: [ "ppc64el", "s390x" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          # snapcraft remote-build requires a full clone
          fetch-depth: 0

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: latest/stable

      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft
          # Setup Launchpad credentials
          mkdir -p ~/.local/share/snapcraft
          echo -e "$LAUNCHPAD_TOKEN" >> ~/.local/share/snapcraft/launchpad-credentials
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions"

      - name: Build Snap (remote)
        run: snapcraft remote-build --build-for=${{ matrix.build-for }} --launchpad-accept-public-upload
      
      - name: Upload snap
        uses: actions/upload-artifact@v5
        with:
          name: prometheus-blackbox-exporter-${{ matrix.build-for }}-snap
          path: "*.snap"
